version: '3.9'

services:
  wttddock:
    image: eventex
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/eventx
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
     - DEBUG=1