version: '3.4'

services:
  eventex:
    image: eventex
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/code
    depends_on:
      - migration
  migration:
    image: eventex
    command: python manage.py collectstatic --no-input --clear
    command: python manage.py migrate --noinput
    volumes:
      - .:/code
